name: temp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.10+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.4.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.2
  flutter_dash: ^1.0.0
  flutter_mobx: ^2.2.0+2
  flutter_platform_alert: ^0.5.1
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  google_maps_flutter: ^2.3.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  intl: ^0.18.0
  map_launcher: ^3.1.0
  mobx: ^2.3.0+1
  package_info_plus: ^4.1.0
  path_provider: ^2.1.2
  pdf_viewer_plugin: ^2.0.1
  provider: ^6.1.2
  rate_my_app: ^2.1.0
  share: ^2.0.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  string_to_color: ^2.0.0
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  sentry_flutter: ^8.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.6.0+1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  assets:
   - assets/image/
   - assets/svg/